package input

Key_Code :: enum u8 {
    KB_ESC          = 9,
    KB_1            = 10,
    KB_2            = 11,
    KB_3            = 12,
    KB_4            = 13,
    KB_5            = 14,
    KB_6            = 15,
    KB_7            = 16,
    KB_8            = 17,
    KB_9            = 18,
    KB_0            = 19,
    KB_DASH         = 20,
    KB_EQUAL        = 21,
    KB_BCKSPC       = 22,
    KB_TAB          = 23,
    KB_Q            = 24,
    KB_W            = 25,
    KB_E            = 26,
    KB_R            = 27,
    KB_T            = 28,
    KB_Y            = 29,
    KB_U            = 30,
    KB_I            = 31,
    KB_O            = 32,
    KB_P            = 33,
    KB_LEFT_BRCKT   = 34,
    KB_RIGHT_BRCKT  = 35,
    KB_ENTER        = 36,
    KB_LEFT_CTRL    = 37,         
    KB_A            = 38,
    KB_S            = 39,
    KB_D            = 40,
    KB_F            = 41,
    KB_G            = 42,
    KB_H            = 43,
    KB_J            = 44,
    KB_K            = 45,
    KB_L            = 46,
    KB_COLON        = 47,
    KB_QUOTES       = 48,
    KB_BACKTICK     = 49,
    KB_LEFT_SHIFT   = 50,
    KB_BACK_SLASH   = 51,
    KB_Z            = 52,
    KB_X            = 53,
    KB_C            = 54,
    KB_V            = 55,
    KB_B            = 56,
    KB_N            = 57,
    KB_M            = 58,
    KB_COMMA        = 59,
    KB_DOT          = 60,
    KB_FWD_SLASH    = 61,
    KB_RIGHT_SHIFT  = 62,
    KB_LEFT_ALT     = 64,
    KB_SPACE        = 65,
    // TODO: CAPSLOCK???
    KB_F1           = 67,
    KB_F2           = 68,
    KB_F3           = 69,
    KB_F4           = 70,
    KB_F5           = 71,
    KB_F6           = 72,
    KB_F7           = 73,
    KB_F8           = 74,
    KB_F9           = 75,
    KB_F10          = 76,
    KB_F11          = 95,
    KB_F12          = 96,

    KB_RIGHT_CTRL   = 105,
    KB_RIGHT_ALT    = 108,

    KB_HOME         = 110,
    KB_UP           = 111,
    KB_LEFT         = 113,
    KB_RIGHT        = 114,
    KB_END          = 155,
    KB_DOWN         = 116,
    KB_INSERT       = 118,
    KB_DEL          = 119,

    KB_LEFT_SUPER   = 133,
}

MouseBtn_Code :: enum {
    LMB = 1,
    MMB = 2,
    RMB = 3,
    REDO = 9,
    UNDO = 8,
}
